# Generated by Django 3.1.7 on 2021-03-06 06:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizningIshlarimiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Mavzu')),
                ('short_info', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='bizning-ishlar', verbose_name='Surat')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('full_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'lik ma'lumot")),
            ],
            options={
                'verbose_name': 'Bizning Ish',
                'verbose_name_plural': 'Bizning Ishlarimiz',
                'db_table': 'bizning_ishlar',
            },
        ),
        migrations.CreateModel(
            name='Korxona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Korxona nomi')),
                ('telegram', models.CharField(max_length=100, verbose_name='Korxona egasining telegram ID si')),
                ('main_image', models.ImageField(upload_to='korxona-haqida', verbose_name='Bosh saxifa uchun surat')),
                ('short_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Qisqacha ma'lumot")),
                ('full_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'liq ma'lumot")),
                ('quote_index_page', models.TextField(verbose_name='Iqtibos')),
                ('quote_name', models.CharField(max_length=250, verbose_name='Iqtibos vakili')),
                ('quote_job', models.CharField(max_length=250, verbose_name='Iqtibos vakilining kasbi')),
                ('quote_image', models.ImageField(upload_to='bizning-ishlar', verbose_name='Iqtibos surat')),
            ],
            options={
                'verbose_name': 'Korxona',
                'verbose_name_plural': 'Korxona',
                'db_table': 'korxona',
            },
        ),
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mijozning ismi')),
                ('phone', models.CharField(max_length=15, verbose_name='Mijozning raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'db_table': 'xabar',
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('speciality', models.CharField(blank=True, max_length=200, verbose_name='Mutaxasisligi')),
                ('info', models.TextField(blank=True, verbose_name="Ma'lumot")),
                ('image', models.ImageField(upload_to='xodimlar', verbose_name='Surat')),
                ('facebook', models.CharField(blank=True, max_length=250, verbose_name='Facebook')),
                ('telegram', models.CharField(blank=True, max_length=250, verbose_name='Telegram')),
                ('insta', models.CharField(blank=True, max_length=250, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Mavzu')),
                ('short_info', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='news', verbose_name='Surat')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('full_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'lik ma'lumot")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
            },
        ),
    ]
