# Generated by Django 3.1.7 on 2021-03-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Mavzu')),
                ('full_info', models.TextField(verbose_name="To'lik ma'lumot")),
                ('short_info', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='news', verbose_name='Surat')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
            },
        ),
    ]
