# Generated by Django 3.1.7 on 2021-03-04 02:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('speciality', models.CharField(blank=True, max_length=200, verbose_name='Mutaxasisiligi')),
                ('info', models.TextField(blank=True, verbose_name="Ma'lumot")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodilmlar',
                'db_table': 'xodimlar',
            },
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='full_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'lik ma'lumot"),
        ),
    ]
