# Generated by Django 3.1.7 on 2021-03-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210304_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='xodim',
            name='insta',
            field=models.CharField(blank=True, max_length=250, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='xodim',
            name='telegram',
            field=models.CharField(blank=True, max_length=250, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='speciality',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mutaxasisligi'),
        ),
    ]
