# Generated by Django 3.1.7 on 2021-03-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210306_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodim',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AddField(
            model_name='xodim',
            name='image',
            field=models.ImageField(default=1, upload_to='xodimlar', verbose_name='Surat'),
            preserve_default=False,
        ),
    ]
