# Generated by Django 3.1.7 on 2021-03-06 02:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210306_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizningIshlarimiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Mavzu')),
                ('short_info', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='bizning-ishlar', verbose_name='Surat')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('full_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'lik ma'lumot")),
            ],
            options={
                'verbose_name': 'BizningIsh',
                'verbose_name_plural': 'BizningIshlarimiz',
                'db_table': 'bizning_ishlar',
            },
        ),
    ]
