# Generated by Django 3.1.7 on 2021-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210306_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korxona',
            name='quote_image',
            field=models.ImageField(upload_to='bizning-ishlar', verbose_name='Iqtibos surat'),
        ),
    ]
