# Generated by Django 3.1.7 on 2021-03-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210306_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korxona',
            name='little_image',
        ),
    ]
