# Generated by Django 3.1.7 on 2021-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_korxona_little_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mijozning ismi')),
                ('phone', models.CharField(max_length=15, verbose_name='Mijozning raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'db_table': 'xabar',
            },
        ),
        migrations.AddField(
            model_name='korxona',
            name='telegram',
            field=models.CharField(default=1, max_length=100, verbose_name='Korxona egasining telegram ID si'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='korxona',
            name='main_image',
            field=models.ImageField(upload_to='korxona-haqida', verbose_name='Bosh saxifa uchun surat'),
        ),
    ]
